### ISSUE TITLE
As a guest, I want to see popular guitars on homepage so that I can know current trends

### ISSUE THREAD

**Issue by waiyan13** [waiyan13/kima-guitar-ui#1]
## Acceptance Criteria

Feature: Homepage

    Scenario: the user visit the sites
        Given the user has correct URL
        When the user visits the site
        Then the user should see images of popular guitars

## Tasks List

- [ ] Create title bar
- [ ] Create hero section
- [ ] Create popular guitars section
- [ ] Fetch images from API
